SRA/Assist/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('asistencia/marcar', views.create_asistencia, name='createAsistencia'),
    path('asistencia/listar', views.listAsistencias, name="listAsists"),
    path('horario/crear', views.create_horario, name="createHorario"),
]

SRA/SRA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Course.urls')),
    path('', include('Assist.urls')),
    path('', include('User.urls')),
    path('', include('Vacation_Permit.urls')),
    path('admin/', admin.site.urls),
    #path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

SRA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Course.urls')),
    path('', include('Assist.urls')),
    path('', include('User.urls')),
    path('', include('Vacation_Permit.urls')),
]

SRA/Assist/models.py
from django.db import models
from User.models import Empleado
from django.utils import timezone
# Create your models here.
import datetime


class Asistencia_Empleado(models.Model):
    cedula = models.ForeignKey(Empleado, on_delete=models.DO_NOTHING, related_name="fk_asistencia_cedula")
    fecha_hora_asitencia = models.DateTimeField(auto_now_add=True)
    llegaTarde = models.BooleanField(default=False)
    falta = models.BooleanField(default=False)
    observacion = models.CharField(
        unique=False, 
        null=True,
        blank=True,
        max_length=45)
    def __str__(self):
        return self.observacion
    
    
class Hora(models.Model):
    hora_entrada = models.TimeField(
        default = None,
        null = False,
        blank = True
        )
    hora_salida = models.TimeField(
        default = None,
        null = False,
        blank = True
        )

class Horario(models.Model):
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, related_name="fk_horario_empleado")
    lunes = models.ForeignKey(Hora, on_delete=models.CASCADE, related_name="fk_hora_lunes", null = True, default=None)
    martes = models.ForeignKey(Hora, on_delete=models.CASCADE, related_name="fk_hora_martes", null = True, default=None)
    miercoles = models.ForeignKey(Hora, on_delete=models.CASCADE, related_name="fk_hora_miercoles", null = True, default=None)
    jueves = models.ForeignKey(Hora, on_delete=models.CASCADE, related_name="fk_hora_jueves", null = True, default=None)
    viernes = models.ForeignKey(Hora, on_delete=models.CASCADE, related_name="fk_hora_viernes", null = True, default=None)
    sabado = models.ForeignKey(Hora, on_delete=models.CASCADE, related_name="fk_hora_sabado", null = True, default=None)
    domingo = models.ForeignKey(Hora, on_delete=models.CASCADE, related_name="fk_hora_domingo", null = True, default=None)
    
    @property
    def needsToAssistToday(self):
        now = datetime.datetime.now()
        day = now.strftime("%A")
        match day:
            case 'Monday':
                return self.lunes
            case 'Tuesday':
                return self.martes
            case 'Wednesday':
                return self.miercoles
            case 'Thursday':
                return self.jueves
            case 'Friday':
                return self.viernes
            case 'Saturday':
                return self.sabado
            case 'Sunday':
                return self.domingo
            case _:
                return None

SRA/Assist/forms.py
from django.forms import ModelForm, fields
from django import forms
from .models import Asistencia_Empleado, Horario, Hora

class createAsistenciaForm(forms.ModelForm):
    class Meta:
            model = Asistencia_Empleado
            fields = ['observacion']
            widgets = {
                'observacion': forms.TextInput(attrs={
                    'required': False
                })
            }
        
class createHoraForm(forms.ModelForm):
    class Meta:
        model = Hora
        fields = ['hora_entrada','hora_salida']
        widgets = {
            'hora_entrada': forms.TimeInput(attrs={
                'type': 'Time',
                'class': 'input',
                'required': False
            }),
            'hora_salida':  forms.TimeInput(attrs={
                'type': 'Time',
                'class': 'input',
                'required': False
            })
        }

SRA/Assist/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db import IntegrityError, OperationalError
from django.contrib.auth.decorators import login_required

from Assist.models import Asistencia_Empleado
from .forms import createAsistenciaForm, createHoraForm
from .models import Horario, Asistencia_Empleado, Horario
from User.models import Empleado
from Assist.models import Hora, Horario
from .utils import str_to_time, needsToAssist, getDay

import datetime
from django.utils import timezone

# Create your views here.
@login_required
def asistencia(request):
    return render(request, 'asistencia.html')

@login_required
def create_asistencia(request):
    epa = Empleado.objects.get(cuenta_usuario=request.user)
    if request.method == 'GET':
        now = timezone.now()
        now = now.replace(hour=0, minute=0, second=0, microsecond=0)
        assists = Asistencia_Empleado.objects.filter(cedula=epa)
        assists.filter(fecha_hora_asitencia__gte=now)
        if assists.count() != 0:
            return render(request, 'createAsistencia.html',{
            'epa': epa,
            'flag_already_marked': True,
            'success': True,
            'home_flag': True 
            })
        else:            
            return render(request, 'createAsistencia.html', {
                'form': createAsistenciaForm,
                'epa':epa,
                'home_flag': True,
            })
    if request.method == 'POST':
        try:
            # horario = Horario.objects.filter(empleado=epa)
            # dia = getDay(horario)
            # result = needsToAssist(dia.hora_entrada, dia.hora_salida)
            # if result:
            now = timezone.now()
            now = now.replace(hour=0, minute=0, second=0, microsecond=0)
            assists = Asistencia_Empleado.objects.filter(cedula=epa)
            assists.filter(fecha_hora_asitencia__gte=now)
            # assists = assists.filter(falta=True)
            if assists.count() != 0:
                return render(request, 'createAsistencia.html',{
                'epa': epa,
                'flag_already_marked': True,
                'success': False,
                'home_flag': True,
                'error_message': 'La asistencia ya fue marcada'
            })
            form = createAsistenciaForm(request.POST)
            push = form.save(commit=False)
            push.cedula = Empleado.objects.get(cuenta_usuario=request.user)
            push.save()
            return render(request, 'createAsistencia.html',{
                'epa': epa,
                'success': True
            })
        except Exception as e:
            print(e)
            return render(request, 'createAsistencia.html',{
                'epa': epa,
                'form': createAsistenciaForm,
                'success': False
            })

@login_required
def listAsistencias(request):
    assists = Asistencia_Empleado.objects.filter( cedula = Empleado.objects.get(cuenta_usuario=request.user)).order_by('-fecha_hora_asitencia')
    epa = Empleado.objects.get(cuenta_usuario=request.user)
    return render(request, 'listAsistencia.html', {'Asistencias': assists,
                                                   'epa': epa})

def create_horario(request):
    epa = Empleado.objects.get(cuenta_usuario=request.user)
    if request.method == 'GET':
        return render(request, 'createHorario.html',{
            'formLunes': createHoraForm,
            'formMartes': createHoraForm,
            'formMiercoles': createHoraForm,
            'formJueves': createHoraForm,
            'formViernes': createHoraForm,
            'formSabado': createHoraForm,
            'formDomingo': createHoraForm,
            'epa': epa
        })
    if request.method == 'POST':
        hora_entradas = request.POST.getlist('hora_entrada')
        hora_salidas = request.POST.getlist('hora_salida')
        horario = Horario()
        for i in range(0,7):
            hora_entrada = str_to_time(hora_entradas[i])
            hora_salida = str_to_time(hora_salidas[i])
            if hora_entrada != None and hora_salida != None:
                if hora_entrada <= hora_salida:
                    if i == 0:
                        h = Hora(hora_entrada=hora_entrada,hora_salida=hora_salida)
                        h.save()
                        horario.lunes = h
                    elif i == 1:
                        h1 = Hora(hora_entrada=hora_entrada,hora_salida=hora_salida)
                        h1.save()
                        horario.martes = h1
                    elif i == 2:
                        h2 = Hora(hora_entrada=hora_entrada,hora_salida=hora_salida)
                        h2.save()
                        horario.miercoles = h2
                    elif i == 3:
                        h3 = Hora(hora_entrada=hora_entrada,hora_salida=hora_salida)
                        h3.save()
                        horario.jueves = h3
                    elif i == 4:
                        h4 = Hora(hora_entrada=hora_entrada,hora_salida=hora_salida)
                        h4.save()
                        horario.viernes = h4
                    elif i == 5:
                        h5 = Hora(hora_entrada=hora_entrada,hora_salida=hora_salida)
                        h5.save()
                        horario.sabado = h5
                    elif i == 6:
                        h6 = Hora(hora_entrada=hora_entrada,hora_salida=hora_salida)
                        h6.save()
                        horario.domingo = h6
                else:
                    return render(request, 'createHorario.html', {
                    'formLunes': createHoraForm,
                    'formMartes': createHoraForm,
                    'formMiercoles': createHoraForm,
                    'formJueves': createHoraForm,
                    'formViernes': createHoraForm,
                    'formSabado': createHoraForm,
                    'formDomingo': createHoraForm,
                    'epa': epa,
                    'success': False,
                    'error_msg': "La hora que finaliza el día no debe ser superior a la hora de inicio"
                })
        horario.empleado = epa
        horario.save()
        return render(request, 'createHorario.html', {
            'formLunes': createHoraForm,
            'formMartes': createHoraForm,
            'formMiercoles': createHoraForm,
            'formJueves': createHoraForm,
            'formViernes': createHoraForm,
            'formSabado': createHoraForm,
            'formDomingo': createHoraForm,
            'epa': epa,
            'success': True,
        })

        

SRA/Assist/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>SRA</title>
  <link rel="icon" href="{% static 'Univalle.svg'%}" type="image/x-icon">
  <meta name="Sistema de registro de Asistencia sede Yumbo" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no "/>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
</head>

<body>
  <nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div id="navbarBasicExample" class="navbar-menu">
        <a class="navbar-item" href="/"><img src="{% static 'Univalle.svg'%} " width="60" height="50"></a>

    {% if user.is_authenticated %}
        <!-assist navbar menu--> 
        <div class="navbar-start">
          <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">Asistencia</a>
          <div class="navbar-dropdown">
            <a class="navbar-item" href="/asistencia/marcar">Registrar asistencia</a>
            <a class="navbar-item" href="/asistencia/listar">Ver registro de asistencia</a>
          </div>
        </div>

          <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">Permisos y Vacaciones</a>
          <div class="navbar-dropdown">
            <a class="navbar-item" href="/permiso/crear">Registrar permisos</a>
            <a class="navbar-item" href="/permiso/listado">Ver permisos</a>

            <hr class="navbar-divider">

            <a class="navbar-item" href="/vacacion/crear">Registrar Vacaciones</a>
            <a class="navbar-item" href="/vacacion/listado">Ver Vacaciones</a>
          </div>
        </div>


    {% if epa.cargo.nombre_cargo == 'Admin'%}
    <!-admin navbar menu--> 
    <div class="navbar-item has-dropdown is-hoverable">
      <a class="navbar-link">Admin</a>
      <div class="navbar-dropdown">
        <a class="navbar-item" href="/admin/createCargo">Crear cargo</a>
        <a class="navbar-item" href="/admin/createDependencia">Crear dependencia</a>
      </div>
    </div>
    
    {% endif %}
  </div>
    <div class="navbar-end">
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-item"><strong>{{epa.nombres|upper}} {{epa.apellidos|upper}}</strong></a>
        <div class="navbar-dropdown is-right">
          <a class="navbar-item" href="/user/update">Actualizar datos</a>
          <hr class="navbar-divider">
          <a class="navbar-item" href="/horario/crear">Crear horario</a>
          <hr class="navbar-divider">
          <a class="navbar-item" href="/logout">Cerrar sesión</a>
        </div>
      </div>

    {% else %}
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary" href="/signin">
            <strong>Iniciar sesión</strong></a>
          <a class="button is-primary" href="/signup">Registrarse</a>
        </div>
      </div>
    </div>
    {% endif %}
    </div>
  </nav>

  {% block content %}



  {% endblock %}

  <div class="main">
    <div class="section"></div>
    <footer class="footer has-">
      <div class="content has-text-centered">
        <p>
          <strong>SRA</strong> hecho por <a href="https://github.com/Erio56">Brayan Andrés Cataño Sánchez</a> y Felipe
          Muñoz.
        </p>
        <img src="{% static 'Univalle.svg'%} " width="60" height="50">
        <p>sede Yumbo</p>
      </div>
    </footer>  
  </div>


</body>

</html>

SRA/Assist/templates/createAsistencia.html
{% extends 'base.html' %}
{% block content %}
<div>
    <div class="container is-is-max-desktop mt-6 mb-6">
        <p class="title">Registrar asistencia</p>
    </div>
    <form action="/asistencia/marcar" method="POST">
        {% csrf_token %}
        <div class="container is-max-desktop mb-5">
            {% if home_flag != True %}
                {% if success %}
                <article class="message is-success">
                    <div class="message-header">
                        <p>Epa guardado</p>
                    </div>
                    <div class="message-body">
                        Se ha registrado <strong>correctamente</strong> la asistencia.
                    </div>
                </article>
                {% else %}
                <article class="message is-danger">
                    <div class="message-header">
                        <p>Error</p>
                    </div>
                    <div class="message-body">
                        Error en la apliación, no se ha registrado la asistencia
                    </div>
                </article>
                {% endif%}
            {% endif %}
        </div>
        {% if flag_already_marked %}
        <div class="container is-max-desktop">
            <p class="">La asistencia fue ya marcada</p>
        </div>
        {% else %}
        {% if not success  %}
        <div class="container is-max-desktop">
            <form action="/asistencia/marcar/" method="POST">
                <div class="box">
                    <div class="field">
                        <label for="id_observacion" class="label">Observación</label>
                            <div class="control">
                                <input name="observacion" for="observacion" required id="id_observacion" class="input" type="text">
                            </div>
                        </div>
                    <div class="container is-max-desktop has-text-centered">
                        <button class="button is-primary ">Marcar Asistencia</button>
                    </div>
            </form>
        </div>
        {% endif %}
        {% endif %}

    </div>
    </form>
</div>
{% endblock %}

SRA/Assist/templates/createHorario.html
{% extends 'base.html' %}

{% block content %}

<div class="container is-max-desktop mt-6">
   {% if success != None %}
   {% if success %}
   <article class="message is-success">
      <div class="message-header">
         <p>Epa guardado</p>
      </div>
      <div class="message-body">
         Se han registrado <strong>correctamente</strong> el horario.
      </div>
   </article>
   {% else %}
   <article class="message is-danger">
      <div class="message-body">
         Se han registrado <strong>incorrectamente </strong> el horario.
         <div><strong>Razón: </strong>{{error_msg}}.</div>
      </div>
   </article>
   {% endif %}
   {% endif %}
</div>

<div class="container is-max-desktop mt-6 mb-4">
   <p class="title">Horario</p>
</div>
<div class="container is-max-desktop">
   <div class="box">
      <form action="/horario/crear" method="POST">
         {% csrf_token %}
         <div class="box"> <strong>Lunes</strong>{{formLunes.as_div}}</div>
         <div class="box"> <strong>Martes</strong>{{formMartes.as_div}}</div>
         <div class="box"> <strong>Miércoles</strong>{{formMiercoles.as_div}}</div>
         <div class="box"> <strong>Jueves</strong>{{formJueves.as_div}}</div>
         <div class="box"> <strong>Viernes</strong>{{formViernes.as_div}}</div>
         <div class="box"> <strong>Sábado</strong>{{formSabado.as_div}}</div>
         <div class="box"> <strong>Domingo</strong>{{formDomingo.as_div}}</div>
         <div class="buttons is-centered">
            <button class="button is-primary">
               Crear
            </button>
         </div>
      </form>
   </div>
</div>

{% endblock %}

SRA/Assist/templates/listAsistencia.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div>
    <div class="container is-is-max-desktop mt-6 mb-6">
        <p class="title">Asistencias</p>
    </div>

    {% load tz %}

    <div class="container is-max-desktop">  
        <div class="box">
            {% if Asistencias|length != 0 %}
            {% for empleado in Asistencias %}
            <h1 class="block"> 
                {% if empleado.falta %}
                ❌<strong>FALTA </strong>{{empleado.fecha_hora_asitencia.date}}
                {% else %}
                ✅{{empleado.fecha_hora_asitencia.date}} a las {{empleado.fecha_hora_asitencia.time}}
                {% endif %}
                {% if empleado.observacion != "" %}
                <strong>- Observación: </strong>{{empleado.observacion}}
                {% endif %}
            </h1>
            {% endfor %}
            {% else %}
                <h1 class="block"> <strong>No se han encontrado registros de asistencias, por favor registre asistencia.</strong> </h1>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}